package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Axel
 */
public class LoginPanel extends javax.swing.JPanel {

    DictFrame d;
    protected boolean isLogin;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(DictFrame d) {
        initComponents();
        this.d = d;
        salahLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        unameTxtField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        passTxtField = new javax.swing.JPasswordField();
        salahLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();

        setLayout(null);

        jLabel2.setText("Password");
        add(jLabel2);
        jLabel2.setBounds(87, 141, 46, 14);
        add(unameTxtField);
        unameTxtField.setBounds(148, 100, 150, 20);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        add(loginButton);
        loginButton.setBounds(144, 194, 66, 23);

        jLabel1.setText("Username");
        add(jLabel1);
        jLabel1.setBounds(90, 103, 48, 14);
        add(passTxtField);
        passTxtField.setBounds(148, 138, 150, 20);

        salahLabel.setText("Username atau Password salah!");
        add(salahLabel);
        salahLabel.setBounds(144, 169, 154, 14);

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        add(resetButton);
        resetButton.setBounds(228, 194, 70, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String username=unameTxtField.getText();
        String pass=passTxtField.getPassword()+"";
        if (d.controller.login(username, pass)) {
            d.enter(1);
            this.isLogin=true;
        } else {
            salahLabel.setVisible(true);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        unameTxtField.setText("");
        passTxtField.setText("");
        salahLabel.setVisible(false);
    }//GEN-LAST:event_resetButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passTxtField;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel salahLabel;
    private javax.swing.JTextField unameTxtField;
    // End of variables declaration//GEN-END:variables
}
